config/routes.rb
Rails.application.routes.draw do
  resources :cohorts_teachers
  resources :cohorts_students
devise_for :users, controllers: { registrations: "users/registrations"}

  resources :cohorts
  resources :courses
  resources :teachers
  resources :students
    
   
post "/cohorts/:id/edit", to: "cohorts_students#create"    
  root "welcome#index"
end

app/models/cohorts_student.rb
class CohortsStudent < ApplicationRecord
    belongs_to :student
    belongs_to :cohort
end

app/controllers/cohorts_students_controller.rb
class CohortsStudentsController < ApplicationController
  before_action :set_cohorts_student, only: [:show, :edit, :update, :destroy]

  # GET /cohorts_students
  # GET /cohorts_students.json
  def index
    @cohorts_students = CohortsStudent.all
  end

  # GET /cohorts_students/1
  # GET /cohorts_students/1.json
  def show
  end

  # GET /cohorts_students/new
  def new
    @cohorts_student = CohortsStudent.new
  end

  # GET /cohorts_students/1/edit
  def edit
  end

  # POST /cohorts_students
  # POST /cohorts_students.json
  def create
    @cohorts_student = CohortsStudent.new(cohorts_student_params)

    respond_to do |format|
      if @cohorts_student.save
        format.html { redirect_to cohort_path(@cohorts_student.cohort_id), notice: 'Cohorts student was successfully created.' }
        format.json { render :show, status: :created, location: @cohorts_student }
      else
        format.html { render :new }
        format.json { render json: @cohorts_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cohorts_students/1
  # PATCH/PUT /cohorts_students/1.json
  def update
    respond_to do |format|
      if @cohorts_student.update(cohorts_student_params)
        format.html { redirect_to @cohorts_student, notice: 'Cohorts student was successfully updated.' }
        format.json { render :show, status: :ok, location: @cohorts_student }
      else
        format.html { render :edit }
        format.json { render json: @cohorts_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cohorts_students/1
  # DELETE /cohorts_students/1.json
  def destroy
    @cohorts_student.destroy
    respond_to do |format|
      format.html { redirect_to cohorts_students_url, notice: 'Cohorts student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cohorts_student
      @cohorts_student = CohortsStudent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cohorts_student_params
      params.require(:cohorts_student).permit(:cohort_id, :student_id)
    end
end

app/helpers/cohorts_students_helper.rb
module CohortsStudentsHelper
end

app/views/cohorts_students/_form.html.erb
<%= form_with(model: cohorts_student, local: true) do |form| %>
  <% if cohorts_student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cohorts_student.errors.count, "error") %> prohibited this cohorts_student from being saved:</h2>

      <ul>
      <% cohorts_student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cohort_id %>
    <%= form.number_field :cohort_id %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cohorts_students/edit.html.erb
<h1>Editing Cohorts Student</h1>

<%= render 'form', cohorts_student: @cohorts_student %>

<%= link_to 'Show', @cohorts_student %> |
<%= link_to 'Back', cohorts_students_path %>

app/views/cohorts_students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cohorts Students</h1>

<table>
  <thead>
    <tr>
      <th>Cohort</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cohorts_students.each do |cohorts_student| %>
      <tr>
        <td><%= cohorts_student.cohort_id %></td>
        <td><%= cohorts_student.student_id %></td>
        <td><%= link_to 'Show', cohorts_student %></td>
        <td><%= link_to 'Edit', edit_cohorts_student_path(cohorts_student) %></td>
        <td><%= link_to 'Destroy', cohorts_student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cohorts Student', new_cohorts_student_path %>

app/views/cohorts_students/new.html.erb
<h1>New Cohorts Student</h1>

<%= render 'form', cohorts_student: @cohorts_student %>

<%= link_to 'Back', cohorts_students_path %>

app/views/cohorts_students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cohort:</strong>
  <%= @cohorts_student.cohort_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @cohorts_student.student_id %>
</p>

<%= link_to 'Edit', edit_cohorts_student_path(@cohorts_student) %> |
<%= link_to 'Back', cohorts_students_path %>