config/routes.rb
Rails.application.routes.draw do
  resources :cohorts_teachers
  resources :cohorts_students
devise_for :users, controllers: { registrations: "users/registrations"}

  resources :cohorts
  resources :courses
  resources :teachers
  resources :students
    
   
post "/cohorts/:id/edit", to: "cohorts_students#create"    
  root "welcome#index"
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    belongs_to :cohort
    
    def teacher_full_name
 "#{first_name} #{last_name}"
end        
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:first_name, :last_name, :age, :salary, :education, :cohort_id)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container text-center">
  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_field :salary %>
  </div>

  <div class="field">
    <%= form.label :education %>
    <%= form.select :education, ["HS", "College", "Masters", "PH.D"] %>
  </div>
    
  <div class="field">
    <%= form.label :cohort_id %>
    <%= form.select :cohort_id, Cohort.all.map { |cohort| [cohort.name, cohort.id] } %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
    </div>
<% end %>

app/views/teachers/edit.html.erb
<h1 class="text-center">Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>
<div class="text-center">
<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>
</div>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Teachers</h1>

<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Education</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.age %></td>
        <td><%= teacher.salary %></td>
        <td><%= teacher.education %></td>
          
        <td><%= link_to 'Show More Info', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1 class="text-center">New Teacher</h1>

<%= render 'form', teacher: @teacher %>
<div class="text-center">
<%= link_to 'Back', teachers_path %>
</div>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @teacher.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teacher.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @teacher.age %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @teacher.salary %>
</p>

<p>
  <strong>Education:</strong>
  <%= @teacher.education %>
</p>
<p>
  <strong>Cohort:</strong>
  <%= Cohort.find(@teacher.cohort_id).name%>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>