config/routes.rb
Rails.application.routes.draw do
  resources :cohorts_teachers
  resources :cohorts_students
devise_for :users, controllers: { registrations: "users/registrations"}

  resources :cohorts
  resources :courses
  resources :teachers
  resources :students
    
   
post "/cohorts/:id/edit", to: "cohorts_students#create"    
  root "welcome#index"
end

app/helpers/cohorts_teachers_helper.rb
module CohortsTeachersHelper
end

app/views/cohorts_teachers/_form.html.erb
<%= form_with(model: cohorts_teacher, local: true) do |form| %>
  <% if cohorts_teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cohorts_teacher.errors.count, "error") %> prohibited this cohorts_teacher from being saved:</h2>

      <ul>
      <% cohorts_teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cohort_id %>
    <%= form.number_field :cohort_id %>
  </div>

  <div class="field">
    <%= form.label :teacher_id %>
    <%= form.number_field :teacher_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cohorts_teachers/edit.html.erb
<h1>Editing Cohorts Teacher</h1>

<%= render 'form', cohorts_teacher: @cohorts_teacher %>

<%= link_to 'Show', @cohorts_teacher %> |
<%= link_to 'Back', cohorts_teachers_path %>

app/views/cohorts_teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cohorts Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Cohort</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cohorts_teachers.each do |cohorts_teacher| %>
      <tr>
        <td><%= cohorts_teacher.cohort_id %></td>
        <td><%= cohorts_teacher.teacher_id %></td>
        <td><%= link_to 'Show', cohorts_teacher %></td>
        <td><%= link_to 'Edit', edit_cohorts_teacher_path(cohorts_teacher) %></td>
        <td><%= link_to 'Destroy', cohorts_teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cohorts Teacher', new_cohorts_teacher_path %>

app/views/cohorts_teachers/new.html.erb
<h1>New Cohorts Teacher</h1>

<%= render 'form', cohorts_teacher: @cohorts_teacher %>

<%= link_to 'Back', cohorts_teachers_path %>

app/views/cohorts_teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cohort:</strong>
  <%= @cohorts_teacher.cohort_id %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @cohorts_teacher.teacher_id %>
</p>

<%= link_to 'Edit', edit_cohorts_teacher_path(@cohorts_teacher) %> |
<%= link_to 'Back', cohorts_teachers_path %>